# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-20 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20160424_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rating',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating_info',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
