# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-20 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0008_auto_20151208_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(default=-1),
        ),
    ]
