# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-28 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_auto_20151015_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='comment_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcement',
            name='last_updated_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='problem_id',
            field=models.IntegerField(null=True),
        ),
    ]
