# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-29 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_auto_20170728_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='problem_id',
            field=models.IntegerField(default=0),
        ),
    ]
