# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-20 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0014_problem_spj_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='subtask',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='subtask_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
